---
# ------------------ Training configurations ------------------------
seed: 456
#------ optimizer
optimizer:
  weight_decay: 0
  lr: 0.0001
  weight_loss: True # (1-K)^-1 weighting? (for Noisier2Noise only)
  batch_size: 5
  epochs: 150

#----- data loader
data:
  location: /home/xsd618/data/fastMRI_test_subset_brain # location of data
  us_fac: 4 # acceleration factor of first mask
  us_fac_lambda: 2 # acceleration factor of second mask
  method: ssdu # choose from "full", "n2n", "ssdu" and "ssdu_bern" for fully supervised, Noisier2Noise, proposed SSDU or original SSDU
  sample_type: columns # choose from "columns" or "bern"
  fully_samp_size: 8 # fully sampled central region
  poly_order: 8 # polynomial order of variable density scheme
  nx: 640
  ny: 320
  nc: 16

#----- network params
network:
  ncascades: 5 # number of VarNet parameters