---
# ------------------ Training configurations ------------------------
seed: 100               # seed to initialize random number generators

#------ optimizer
optimizer:
  name: Adam
  weight_decay: 0
  momentum: 0.9
  lr: 0.0001
  decay_milestones: [] #[5, 10, 30] # which epoch does the lr decay
  loss: mse # l1, mse or rmse
  weight_loss: True
  batch_size: 5
  epochs: 150
  load_model_loc: 0

#----- configure the data loader
data:
  us_fac: 4
  us_fac_lambda: 4
  method: n2n
  sample_type: columns
  train_trunc: 10000000
  val_trunc: 2000000
  multicoil: True
  nx: 640
  ny: 320
  nc: 16
  fully_samp_size: 8
  poly_order: 8

#----- network params
network:
  device: cuda     # uses cpu if gpu not available
  type: varnet
  ncascades: 5